api_platform:
    title: 'Banking & Insurance API'
    description: 'API pour syst√®me Banque/Assurance - Test hydrateur'
    version: '1.0.0'
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
    swagger_ui:
        enabled: true
